In [10]:
import re

---
Anchors

---

In [1]:
import numpy
print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print (sampleArray)
print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1)
print (sampleArray)
arr = numpy.array([[10,10,10]])
print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1)
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


---
0 or 11 or 101

---

In [16]:
pattern_1 = r"^(0|11|101)$"

user = input("Enter a string (0, 11, or 101): ")

if re.match(pattern_1, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string (0, 11, or 101): 11
'11' matches the pattern


---
only 0s

---

In [18]:
pattern_2 = r"^0*$"
user = input("Enter a string of only 0s: ")

if re.match(pattern_2, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string of only 0s: 21
'21' does NOT match the pattern


---
all binary strings

---

In [22]:
pattern_3 = r"^(0|1)*$"

user = input("Enter a binary string (only 0s and 1s): ")

if re.match(pattern_3, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a binary string (only 0s and 1s): 010101
'010101' matches the pattern


---
all binary strings except empty string

---

In [24]:
pattern_4 = r"^(0|1)+$"

user = input("Enter a non-empty binary string: ")

if re.match(pattern_4, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a non-empty binary string: 101
'101' matches the pattern


---
begins with 1, ends with 1

---

In [25]:
pattern_5 = r"^1(0|1)*1$"

user = input("Enter a string that begins and ends with 1: ")

if re.match(pattern_5, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that begins and ends with 1: 10001
'10001' matches the pattern


---
ends with 00

---

In [26]:
pattern_6 = r"^(0|1)*00$"

user = input("Enter a string that ends with 00: ")

if re.match(pattern_6, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that ends with 00: 111100
'111100' matches the pattern


---
contains at least three 1s

---

In [19]:
pattern_7 = r"^(0|1)*1(0|1)*1(0|1)*1(0|1)*$"

user = input("Enter a string that contains at least three 1s: ")

if re.match(pattern_7, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that contains at least three 1s: 11114
'11114' does NOT match the pattern


---
contains at least three consecutive 1s

---

In [27]:
pattern_8 = r"^(0|1)*111(0|1)*$"

user = input("Enter a string that contains at least three consecutive 1s: ")

if re.match(pattern_8, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that contains at least three consecutive 1s: 0101111
'0101111' matches the pattern


---
contains the substring 110

---

In [28]:
pattern_9 = r"^(0|1)*110(0|1)*$"

user = input("Enter a string that contains the substring '110': ")

if re.match(pattern_9, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that contains the substring '110': 01011011
'01011011' matches the pattern


---
doesn't contain the substring 110

---

In [21]:
pattern_10 = r"^(0|10)*1*$"

user = input("Enter a string that does not contain the substring '110': ")

if re.match(pattern_10, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that does not contain the substring '110': 10100
'10100' matches the pattern


---
contains at least two 0s but not consecutive 0s

---


In [32]:
pattern_11 = r"^(1*011*(0+011*))*$"

user = input("Enter a string that contains at least two 0s but not consecutive: ")

if re.match(pattern_11, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that contains at least two 0s but not consecutive: 10110
'10110' does NOT match the pattern


---
has at least 3 characters, and the third character is 0

---

In [33]:
pattern_12 = r"^(0|1)(0|1)0(0|1)*$"

user = input("Enter a string with at least 3 characters and third character as 0: ")

if re.match(pattern_12, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string with at least 3 characters and third character as 0: 110
'110' matches the pattern


---
number of 0s is a multiple of 3

---

In [34]:
pattern_13 = r"^1*|(1*01*01*01*)*$"


user = input("Enter a string where the number of 0s is a multiple of 3: ")

if re.match(pattern_13, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string where the number of 0s is a multiple of 3: 00010100
'00010100' matches the pattern


---
starts and ends with the same character

---

In [35]:
pattern_14 = r"^1(0|1)*1$|^0(0|1)*0$"

user = input("Enter a string that starts and ends with the same character: ")

if re.match(pattern_14, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that starts and ends with the same character: 100001
'100001' matches the pattern


---
odd length

---

In [36]:
pattern_15 = r"^(0|1)((0|1)(0|1))*$"

user = input("Enter a string of odd length: ")

if re.match(pattern_15, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string of odd length: 011
'011' matches the pattern


---
starts with 0 and has odd length, or starts with 1 and has even length

---

In [37]:
pattern_16 = r"^0((0|1)(0|1))*$|^1(0|1)((0|1)(0|1))*$"

user = input("Enter a string that starts with 0 and has odd length, or starts with 1 and has even length: ")

if re.match(pattern_16, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string that starts with 0 and has odd length, or starts with 1 and has even length: 011
'011' matches the pattern


---
length is at least 1 and at most 3

---

In [39]:
pattern_17 = r"^(0|1)$|^(0|1)(0|1)$|^(0|1)(0|1)(0|1)$"

user = input("Enter a string with length between 1 and 3: ")

if re.match(pattern_17, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a string with length between 1 and 3: 0000
'0000' does NOT match the pattern


---
How to find or validate an email address

---

In [40]:
email_pattern = r"^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$"

user = input("Enter an email address: ")

if re.match(email_pattern, user, re.IGNORECASE):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter an email address: sin.com
'sin.com' does NOT match the pattern


---
Matching a Valid Date

---

In [41]:
date_pattern = r"^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$"

user = input("Enter a date (MM/DD/YYYY): ")

if re.match(date_pattern, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


Enter a date (MM/DD/YYYY): 2024/10/2
'2024/10/2' does NOT match the pattern


---
IP Addresses

---

In [ ]:
ip_pattern = r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"

user = input("Enter an IP address: ")

if re.match(ip_pattern, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


---
Match an American Express Credit Card Number which always begin with 34 or 37 and
totals 15 digits.

---

In [ ]:
cc_pattern = r"^3[47]\d{13}$"

user = input("Enter an American Express card number (15 digits, starts with 34 or 37): ")

if re.match(cc_pattern, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")


---
Match a full U.S. Phone Number: +1-(555)-555-5555

---

In [ ]:
phone_pattern = r"^\+1-\(\d{3}\)-\d{3}-\d{4}$"

user = input("Enter a U.S. phone number (+1-(555)-555-5555): ")

if re.match(phone_pattern, user):
    print(f"'{user}' matches the pattern")
else:
    print(f"'{user}' does NOT match the pattern")
