In [1]:
import numpy as np

In [23]:
I = np.identity(3)
print(I)
A = np.reshape(np.arange(24)+1, (8,3))
print(A)
output_gradient = np.random.rand(8,3)
AA = (I - A[:, :, np.newaxis]) * A[:, np.newaxis , :]
# Compute g^(0)T * (I - a^(0)) ⊙ a^(0)T using einsum
result = np.einsum('ij,ijk->ik', output_gradient, AA)

print("\nResult of g^(0)T * (I - a^(0)) ⊙ a^(0)T using einsum:")
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

Result of g^(0)T * (I - a^(0)) ⊙ a^(0)T using einsum:
[[-9.28705729e-01 -2.52203440e+00 -3.70083058e+00]
 [-3.92315203e+01 -4.58180452e+01 -5.62868869e+01]
 [-4.97994423e+01 -5.46510698e+01 -5.98860568e+01]
 [-1.80954169e+02 -1.95281360e+02 -2.20523683e+02]
 [-2.30809265e+02 -2.37236136e+02 -2.66881285e+02]
 [-3.10731809e+02 -3.33574925e+02 -3.44146238e+02]
 [-3.88165449e+02 -3.96028129e+02 -4.27196201e+02]
 [-9.30040174e+02 -9.62260328e+02 -1.01668379e+03]]


In [14]:
A[:,:, np.newaxis]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]],

       [[16],
        [17],
        [18]],

       [[19],
        [20],
        [21]],

       [[22],
        [23],
        [24]]])

In [18]:
AI = I - A[:, :, np.newaxis]
print(AI)

[[[  0.  -1.  -1.]
  [ -2.  -1.  -2.]
  [ -3.  -3.  -2.]]

 [[ -3.  -4.  -4.]
  [ -5.  -4.  -5.]
  [ -6.  -6.  -5.]]

 [[ -6.  -7.  -7.]
  [ -8.  -7.  -8.]
  [ -9.  -9.  -8.]]

 [[ -9. -10. -10.]
  [-11. -10. -11.]
  [-12. -12. -11.]]

 [[-12. -13. -13.]
  [-14. -13. -14.]
  [-15. -15. -14.]]

 [[-15. -16. -16.]
  [-17. -16. -17.]
  [-18. -18. -17.]]

 [[-18. -19. -19.]
  [-20. -19. -20.]
  [-21. -21. -20.]]

 [[-21. -22. -22.]
  [-23. -22. -23.]
  [-24. -24. -23.]]]


In [20]:
result = AI * A[:, np.newaxis , :]
print(result)

[[[   0.   -2.   -3.]
  [  -2.   -2.   -6.]
  [  -3.   -6.   -6.]]

 [[ -12.  -20.  -24.]
  [ -20.  -20.  -30.]
  [ -24.  -30.  -30.]]

 [[ -42.  -56.  -63.]
  [ -56.  -56.  -72.]
  [ -63.  -72.  -72.]]

 [[ -90. -110. -120.]
  [-110. -110. -132.]
  [-120. -132. -132.]]

 [[-156. -182. -195.]
  [-182. -182. -210.]
  [-195. -210. -210.]]

 [[-240. -272. -288.]
  [-272. -272. -306.]
  [-288. -306. -306.]]

 [[-342. -380. -399.]
  [-380. -380. -420.]
  [-399. -420. -420.]]

 [[-462. -506. -528.]
  [-506. -506. -552.]
  [-528. -552. -552.]]]
